#!/bin/bash

mcmWebLoc="localhost/mcManager.php"

# Prefered server version/type
# vanilla
# cb-rec
# cb-beta
# cb-dev
serverType="vanilla"

function getYesNo ()
{	


	output=2
	message=$1
	valid=false
	until [ $valid == true ]
	do
	
	echo -n "$message (y/n): "
	read choice
	choice=$(echo "${choice^^}" )
		case $choice in
			"Y"|"YES")
				output=1
				valid=true
				;;

			"N"|"NO")
				output=0
				valid=true
				;;
		esac
	done

	return $output
}

function getNewVanillaLink ()
{	
	PAGE="https://minecraft.net/download"

	RAW_PAGE=$(wget "$PAGE" -q -O -)
	after='.jar" class="download-link" data-dist="server"'
	before="https"

	end=$(awk -v a="$RAW_PAGE" -v b="$after" 'BEGIN{print index(a,b)}')
	start=`expr $(awk -v a="${RAW_PAGE:$(expr $end - 120):120}" -v b="$before" 'BEGIN{print index(a,b)}') + $end - 121`
	echo "${RAW_PAGE:$start:$(expr $end - $start)}jar"
}

function getNewVanillaVersion ()
{

	PAGE="http://minecraft.gamepedia.com/Minecraft"

	RAW_PAGE=$(wget "$PAGE" -q -O -)
	close="<dt>Computer</dt>"
	after='</a>'
	before="\">"
	HALF_PAGE=${RAW_PAGE:0:$(expr ${#RAW_PAGE} / 2 ) }

	astart=$(awk -v a="$HALF_PAGE" -v b="$close" "BEGIN{print index(a,b)}")
	area=${HALF_PAGE:$astart}

	start=`expr $(awk -v a="$area" -v b="$before" 'BEGIN{print index(a,b)}') + $astart + 1`

	end=$(awk -v a="${HALF_PAGE:$start}" -v b="$after" "BEGIN{print index(a,b)}")
	echo "${HALF_PAGE:$start:$(expr $end - 1)}"

}

function getCurrentVersion ()
{
	echo $(wget "$mcmWebLoc?getCurrentVersion" -q -O -)
}

function checkForVanillaUpdate ()
{
	if [ $(getCurrentVersion) != $(getNewVanillaVersion) ]
	then
		echo "Not Up to Date!"
	else
		echo "Up to date"
	fi
}

function installMinecraft ()
{

	# root test
	if [[ $EUID -ne 0 ]] 
	then
   		echo "You need to run this as root to be able to make system changes"
		echo -e "Run \"sudo $0 $1\" next time"
		exit 1
	fi

	# Setup /var/minecraft
	mkdir /var/minecraft

	# Download program
	case $serverType in 

		'vanilla')
				wget $(getNewVanillaLink) -O /var/minecraft/minecraft-server.jar
			;;
	esac

	# Put files in place
	cp start-minecraft /var/minecraft/minecraft
	ln -s /var/minecraft/minecraft /usr/sbin/minecraft
	cp service-minecraft /etc/init.d/minecraft

	# Accept EULA
	getYesNo "Do you accept the Minecraft server eula (https://account.mojang.com/documents/minecraft_eula)?"
	if [ "$?" == "1" ]
		then
		service minecraft start
		sleep 5
		sed -i 's/^eula=false$/eula=true/' /var/minecraft/eula.txt

	fi

	# Generate Files
	service minecraft start
	sleep 5
	service minecraft stop

	# Link server.properties to /etc
	unlink /etc/minecraft.conf
	ln -s /var/minecraft/server.properties /etc/minecraft.conf

	# Allow Query
	sed -i 's/^enable-query=false$/enable-query=true/' /var/minecraft/server.properties

	# Add ops
	echo -n "Users to op (Seperate with spaces): "
	read ops
	echo "$ops" | sed 's/ /\n/' >> /var/minecraft/ops.txt
	
}

function updatemcManager ()
{

	# root test
	if [[ $EUID -ne 0 ]] 
	then
   		echo "You need to run this as root to be able to make system changes"
		echo -e "Run \"sudo $0 $1\" next time"
		exit 1
	fi

	# Put files in place
	cp start-minecraft /var/minecraft/minecraft
	cp mcManager.php /var/www 
	cp service-minecraft /etc/init.d/minecraft
	
}

case $1 in


	'getNewVanillaLink')
		getNewVanillaLink
		;;

	'getNewVanillaVersion')
		getNewVanillaVersion
		;;

	'getCurrentVersion')
		getCurrentVersion
		;;

	'checkForVanillaUpdate')
		checkForVanillaUpdate
		;;

	'installMinecraft')
		installMinecraft
		;;

	'updatemcManager')
		updatemcManager
		;;


	*)
	    echo "Usage: $0 {getNewVanillaLink|getNewVanillaVersion|getCurrentVersion|checkForVanillaUpdate|installMinecraft|updatemcManager}" >&2
	    exit 3
		;;
esac

