#!/bin/bash

sysdate=$(date +"20%y-%m-%d")
systime=$(date +"%T")

mcDir="/var/minecraftd"

backupDir="/var/minecraftd/backups"
backupsToKeep=5


# Prefered server version/type
# vanilla
# cb-rb
# cb-beta
# cb-dev
serverType="vanilla"


# Include basicFunctions library during development
#    It's kept seperate to make files easier to read
if [ -f './basicFunctions.sh' ]
	then

	source ./basicFunctions.sh
fi

# Insert basicFunctions library during install
#[INSERT_FUNCTIONS_HERE]


# Include webDataParsing library during development
#    It's kept seperate to make files easier to read
if [ -f './webDataParsing.sh' ]
	then

	source ./webDataParsing.sh
fi

# Insert basicFunctions library during install
#[INSERT_WEB_FUNCTIONS_HERE]   


# Include basicFunctions library during development
#    It's kept seperate to make files easier to read
if [ -f './motd.sh' ]
	then

	source ./motd.sh
fi

# Insert basicFunctions library during install
#[INSERT_MOTD_FUNCTIONS_HERE]    


# getCurrentVersion
# 
# Run a copy of the server in the tmp folder to get it's version
function getCurrentVersion ()
{
	# Copy to a new temp directory
	mkdir /tmp/mcManager/
	sudo cp "$mcDir/minecraft-server.jar" /tmp/mcManager/

	# Start the server to generate a log file. It will stop on the eula agreement
	cd /tmp/mcManager/
	java -Xms512M -Xmx1G -jar ./minecraft-server.jar &>> /dev/null

	# Get latest log as raw text
	RAW_PAGE=$(cat /tmp/mcManager/logs/latest.log)

	# Set text that comes before the version number
	before="version "

	# Find the point in the log where the version number
	start=$(awk -v a="$RAW_PAGE" -v b="$before" 'BEGIN{print index(a,b)}')

	# Return the download link as a string after cutting off the end
	echo "$(echo ${RAW_PAGE:$(expr $start + ${#before} - 1 )} | sed 's/\s.*$//' | tail -1 )"

	rm -r /tmp/mcManager/

}


# checkForVanillaUpdate
# 
# Takes the newest version number and compares it to the currently running one to see if they match.
function checkForUpdate ()
{
	if [ "$(getCurrentVersion)" != "$(getNewestVersion)" ]
	then
		echo "Not Up to Date!"
	else
		echo "Up to date"
	fi
}


# autoUpdate
# 
# Checks for any updates and automaticaly applies them
function autoUpdate ()
{
	if [ "$(checkForUpdate)" == "Not Up to Date!" ]
	then
		updateMinecraft
	else
		echo "No update needed"
	fi
}


# installMinecraft
# 
# Installs the Minecraft server and sets it up as a system service
function installMinecraft ()
{

	rootTest

	# Setup /var/minecraftd
	mkdir "$mcDir"

	# Download program
	updateMinecraft

	# Put files in place
	updatemcManager

	# Accept EULA
	getYesNo "Do you accept the Minecraft server eula (https://account.mojang.com/documents/minecraft_eula)?"
	if [ "$?" == "1" ]
		then
		service minecraftd start
        until [ -f "$mcDir/eula.txt" ]
        do
            sleep 1
        done
		sed -i 's/^eula=false$/eula=true/' "$mcDir/eula.txt"

	fi

	# Generate Files
	service minecraftd start
    until [ -f "$mcDir/server.properties" ]
    do
        sleep 1
    done
	service minecraftd stop

	# Link server.properties to /etc
	unlink /etc/minecraftd.conf
	ln -s "$mcDir/server.properties" /etc/minecraftd.conf

	# Add ops
	setOPS

	# set MOTD
	setMOTD
	
}

# changeMOTD
# 
# Sets a new server message of the day
function setMOTD ()
{
	rootTest
	echo "Edit MOTD:"
	currentMOTD=$(convertMOTDfromFile "$(cat "$mcDir/server.properties" | grep motd | sed 's/^motd=//')")
	read -eri "$currentMOTD" motd
	motd=$(convertMOTDtoFile "$motd")
	sed -i s/'motd=.*'/'motd='"$motd"/ "$mcDir/server.properties"
}


# changeMOTD
# 
# Sets a new server message of the day
function setOPS ()
{
	rootTest
	
	currentOps=""
	while read line
	do
		line=$(echo "$line" | tr -d ' ')
			if  [ "$line" != "" ]
				then
					currentOps="$currentOps $line"
			fi
			
	done < "$mcDir/ops.txt"
	currentOps=$(echo $currentOps | sed 's/ *$//')
	read -e -p "Users to op (Seperate with spaces): " -i "$currentOps" ops
	echo "$ops" | sed 's/ *$//' | sed 's/ /\n/' > "$mcDir/ops.txt"
}

# updateMinecraft
# 
# Updates Minecraft
function updateMinecraft ()
{	
	rootTest

	service minecraftd stop

	# Download program
	wget $(getNewLink) -O "$mcDir/minecraft-server.jar"
	
	service minecraftd start
}

# backupMinecraft
# 
# Backs up the entire Minecraft setup and worlds
function backupMinecraft ()
{

	rootTest

	mkdir $backupDir

	backupName="$sysdate-$(getCurrentVersion)-Backup"
	tar -czf $backupDir/$backupName.tar.gz $mcDir
}

# autoBackupMinecraft
# 
# Backs up Minecraft and checks if there are more backups than wanted
function autoBackupMinecraft ()
{

	rootTest

	backupMinecraft

	cd $backupDir

	files=(*)
	numfiles=${#files[@]}
	echo "$backupsToKeep < $numfiles"

	if [ "$backupsToKeep" -lt "$numfiles" ]
		then
			rm "${files[0]}"
	fi

}



# updatemcManager
# 
# Installs all the mcManager files
function updatemcManager ()
{

	rootTest

	# Put files in place
	cp start-minecraft "$mcDir/minecraftd"
	cp "./mcmanager" "$mcDir/mcmanager"
	cp service-minecraft /etc/init.d/minecraftd

	cp "./autocomplete" "$mcDir/autocomplete"
	if grep -q "#mcmanager autocomplete" "/etc/bash.bashrc"
		then
		echo "nothing" >> /dev/null
	else
		echo "source $mcDir/autocomplete #mcmanager autocomplete" >> "/etc/bash.bashrc"
	fi

	if [ ! -f "/usr/sbin/mcmanager" ]
		then
		ln -s "$mcDir/mcmanager" /usr/sbin/mcmanager
	fi
	if [ ! -f "/usr/sbin/minecraftd" ]
		then
		ln -s "$mcDir/minecraftd" /usr/sbin/minecraftd
	fi

	includeScript "./basicFunctions.sh" "#[INSERT_FUNCTIONS_HERE]" "$mcDir/mcmanager"
	includeScript "./webDataParsing.sh" "#[INSERT_WEB_FUNCTIONS_HERE]   " "$mcDir/mcmanager"
	includeScript "./motd.sh" "#[INSERT_MOTD_FUNCTIONS_HERE]    " "$mcDir/mcmanager"
	
	# Set to run on startup
	update-rc.d minecraftd defaults  &>> /dev/null
}


# status
# 
# Returns current information about the server
function status ()
{

	rootTest

	echo "Current Version: $(getCurrentVersion) Newest Version: $(getNewestVersion). $(checkForUpdate)"
}




# Logic
case $1 in


	'getNewLink')
		getNewLink
		;;

	'getNewestVersion')
		getNewestVersion
		;;

	'getCurrentVersion')
		getCurrentVersion
		;;

	'checkForUpdate')
		checkForUpdate
		;;

	'autoUpdate')
		autoUpdate
		;;

	'updateMinecraft')
		updateMinecraft
		;;

	'installMinecraft')
		installMinecraft
		;;

	'setOPS')
		setOPS
		;;

	'setMOTD')
		setMOTD
		;;

	'backupMinecraft')
		backupMinecraft
		;;

	'autoBackupMinecraft')
		autoBackupMinecraft
		;;

	'updatemcManager')
		updatemcManager
		;;

	'status')
		status
		;;

	*)
	    echo "Usage: $0 {getNewLink|getNewestVersion|getCurrentVersion|checkForUpdate|autoUpdate|updateMinecraft|installMinecraft|setOPS|setMOTD|backupMinecraft|autoBackupMinecraft|updatemcManager|status}" >&2
	    exit 3
		;;
esac

